### ISSUE TITLE
is there a convenient way to bundle and compress dep crates?

### ISSUE THREAD

**Issue by WUST-mengqinyu** [to-omer/competitive-library#21]
Hello @to-omer ,
I recently came across your atcoder submission and was impressed by its conciseness. I was wondering if you have used any tools similar to [rust-bundler-cp](https://github.com/Endle/rust-bundler-cp) to automatically integrate truly necessary parts from dependencies. I believe such a tool would greatly enhance my efficiency in coding with Rust and I'd appreciate any suggestion you might have. 
Thanks in advance for your help.
Best Regards.

**Comment by to-omer** [comment]
I use [codesnip](https://github.com/to-omer/codesnip) and its [VSCode extension](https://github.com/to-omer/codesnip-vscode) which allows me to paste code snippets.
It is useful because it has features to paste dependent snippets together, to avoid duplicating snippets once pasted, and to minify snippets.
I am sorry, but these tools are maintained for my own use and are not intended to be used by others.
